#!/bin/bash

# Antud skripti pohimote on luua lause muutujatega

aasta=2021
president="Alar Karis"
lause_keskosa=". aastal valiti Eesti presidendiks "
lause="${aasta}${lause_keskosa}${president}"
echo $lause
